version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - private_network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: 089077
      POSTGRES_DB: TestDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private_network 
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -d TestDB -U postgres"]
     interval: 1s
     timeout: 5s
     retries: 10

networks:
  private_network:
    driver: bridge

volumes:
  postgres_data: